### PR TITLE
Remove library name fetching for unknown and error frames

### LINKED ISSUE #598: ASAN error
Consider the following example:
```
fun fun1() {
    fun2()
}

fun fun2() {
    fun3()
}

fun fun3() {
    val list = listOf(1, 2, 3)
    list.filter { it > 2 }.map { it + 1}
}

fun main() {
    repeat(1000) {
        fun1()
    }
}
```
Compile the profiler with Address Sanitizer:
```
CFLAGS=... -fsanitize=address
CXXFLAGS=... -fsanitize=address
```

When you run this code with the profiler attached, ASAN will occasionally show this error
```
=================================================================
==52685==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00010b89195c at pc 0x00010b86343a bp 0x700006e01130 sp 0x700006e01128
READ of size 2 at 0x00010b89195c thread T2
    #0 0x10b863439 in Profiler::getLibraryName(char const*)+0xc9 (libasyncProfiler.so:x86_64+0x63439)
    #1 0x10b830edd in Lookup::fillNativeMethodInfo(MethodInfo*, char const*)+0xdd (libasyncProfiler.so:x86_64+0x30edd)
    #2 0x10b830c7e in Lookup::resolveMethod(ASGCT_CallFrame&)+0x36e (libasyncProfiler.so:x86_64+0x30c7e)
    #3 0x10b82d9d0 in Recording::writeStackTraces(Buffer*, Lookup*)+0x4a0 (libasyncProfiler.so:x86_64+0x2d9d0)
    #4 0x10b82a8fb in Recording::writeCpool(Buffer*)+0x41b (libasyncProfiler.so:x86_64+0x2a8fb)
    #5 0x10b82955f in Recording::finishChunk()+0x91f (libasyncProfiler.so:x86_64+0x2955f)
    #6 0x10b8286e6 in Recording::~Recording()+0x26 (libasyncProfiler.so:x86_64+0x286e6)
    #7 0x10b81d301 in FlightRecorder::stop()+0x1f1 (libasyncProfiler.so:x86_64+0x1d301)
    #8 0x10b86eabe in Profiler::stop()+0x72e (libasyncProfiler.so:x86_64+0x6eabe)
    #9 0x10b876390 in Profiler::runInternal(Arguments&, std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+0xb0 (libasyncProfiler.so:x86_64+0x76390)
    #10 0x10b876b33 in Profiler::run(Arguments&)+0x333 (libasyncProfiler.so:x86_64+0x76b33)
    #11 0x10b877864 in Profiler::shutdown(Arguments&)+0x64 (libasyncProfiler.so:x86_64+0x77864)
    #12 0x10ca8fd99 in JvmtiExport::post_vm_death()+0x16b (libjvm.dylib:x86_64+0x4d2d99)
    #13 0x10c97a7a1 in before_exit(JavaThread*)+0x29c (libjvm.dylib:x86_64+0x3bd7a1)
    #14 0x10cd49563 in Threads::destroy_vm()+0xb3 (libjvm.dylib:x86_64+0x78c563)
    #15 0x10c9cd006 in jni_DestroyJavaVM+0xd2 (libjvm.dylib:x86_64+0x410006)
    #16 0x101b2686b in JavaMain+0xb0b (libjli.dylib:x86_64+0x486b)
    #17 0x101b28be3 in ThreadJavaMain+0x8 (libjli.dylib:x86_64+0x6be3)
    #18 0x7ff8054474e0 in _pthread_start+0x7c (libsystem_pthread.dylib:x86_64+0x64e0)
    #19 0x7ff805442f6a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1f6a)

0x00010b89195c is located 36 bytes to the left of global variable '<string literal>' defined in 'src/flightRecorder.cpp:155:44' (0x10b891980) of size 5
  '<string literal>' is ascii string '()L;'
0x00010b89195c is located 4 bytes to the left of global variable '<string literal>' defined in 'src/flightRecorder.cpp:227:42' (0x10b891960) of size 8
  '<string literal>' is ascii string 'unknown'
0x00010b89195c is located 19 bytes to the right of global variable '<string literal>' defined in 'src/flightRecorder.cpp:941:35' (0x10b891940) of size 9
  '<string literal>' is ascii string '[tid=%d]'
SUMMARY: AddressSanitizer: global-buffer-overflow (libasyncProfiler.so:x86_64+0x63439) in Profiler::getLibraryName(char const*)+0xc9
Shadow bytes around the buggy address:
  0x1000217122d0: 00 00 03 f9 f9 f9 f9 f9 00 00 00 01 f9 f9 f9 f9
  0x1000217122e0: 00 00 01 f9 f9 f9 f9 f9 00 01 f9 f9 00 00 05 f9
  0x1000217122f0: f9 f9 f9 f9 00 06 f9 f9 00 07 f9 f9 00 00 02 f9
  0x100021712300: f9 f9 f9 f9 03 f9 f9 f9 00 04 f9 f9 00 05 f9 f9
  0x100021712310: 00 f9 f9 f9 07 f9 f9 f9 04 f9 f9 f9 07 f9 f9 f9
=>0x100021712320: 00 07 f9 f9 00 07 f9 f9 00 01 f9[f9]00 f9 f9 f9
  0x100021712330: 05 f9 f9 f9 05 f9 f9 f9 00 f9 f9 f9 00 03 f9 f9
  0x100021712340: 00 00 00 00 07 f9 f9 f9 f9 f9 f9 f9 02 f9 f9 f9
  0x100021712350: 05 f9 f9 f9 06 f9 f9 f9 05 f9 f9 f9 05 f9 f9 f9
  0x100021712360: 00 00 f9 f9 05 f9 f9 f9 05 f9 f9 f9 05 f9 f9 f9
  0x100021712370: 06 f9 f9 f9 06 f9 f9 f9 07 f9 f9 f9 03 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T2 created by T1 here:
    #0 0x101e6367c in wrap_pthread_create+0x5c (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4267c)
    #1 0x101b28b97 in CallJavaMainInNewThread+0x71 (libjli.dylib:x86_64+0x6b97)
    #2 0x101b27812 in ContinueInNewThread+0xa2 (libjli.dylib:x86_64+0x5812)
    #3 0x101b25943 in JLI_Launch+0x19ff (libjli.dylib:x86_64+0x3943)
    #4 0x101a04a84 in main+0x184 (java:x86_64+0x100000a84)
    #5 0x101b2922f in apple_main+0x53 (libjli.dylib:x86_64+0x722f)
    #6 0x7ff8054474e0 in _pthread_start+0x7c (libsystem_pthread.dylib:x86_64+0x64e0)
    #7 0x7ff805442f6a in thread_start+0xe (libsystem_pthread.dylib:x86_64+0x1f6a)

Thread T1 created by T0 here:
    #0 0x101e6367c in wrap_pthread_create+0x5c (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4267c)
    #1 0x101b283d1 in CreateExecutionEnvironment+0x115 (libjli.dylib:x86_64+0x63d1)
    #2 0x101b2452b in JLI_Launch+0x5e7 (libjli.dylib:x86_64+0x252b)
    #3 0x101a04a84 in main+0x184 (java:x86_64+0x100000a84)
    #4 0x11048151d in start+0x1cd (dyld:x86_64+0x551d)

==52685==ABORTING
```

### PR DESCRIPTION
**Pull request by nikita-nazarov**
When fetching info of a native method we try to get its library name by calling `Profiler::instance()->getLibraryName(name)`. However, to fetch this information we perform this cast: `(NativeFunc*)(name - sizeof(NativeFunc))` at `NativeFunc::from`. At the same time, at `Lookup::resolveMethod` we create a mock native frame for methods with a missing method id and assign them the name 'unknown'. For these methods the described cast can never succeed, it also leads to runtime errors if the profiler is compiled with Address Sanitizer. The same error happens with mock event frames with the 'no_Java_frame' name, which are created at `Profiler::recordSample`.

fixes #598

### CODE REVIEW

**Comment by apangin** [comment]
Thanks for the analysis and the fix, it makes perfect sense!

File: src/flightRecorder.cpp [hunk 1]
```diff
@@ -223,9 +222,13 @@ class Lookup {
...
             if (method == NULL) {
-                fillNativeMethodInfo(mi, "unknown");
-            } else if (frame.bci == BCI_NATIVE_FRAME || frame.bci == BCI_ERROR) {
-                fillNativeMethodInfo(mi, (const char*)method);
+                fillNativeMethodInfo(mi, "unknown", NULL);
+            } else if (frame.bci == BCI_ERROR) {
+                fillNativeMethodInfo(mi, (const char*)method, NULL);
+            } else if (frame.bci == BCI_NATIVE_FRAME) {
+                const char* name = (const char*)method;
+                const char* lib_name = name == NULL ? NULL : Profiler::instance()->getLibraryName(name);
```
Comment (apangin) [inline src/flightRecorder.cpp:230]: `name` is never NULL at this point
